---
- name: Get ARP Information
  hosts: all
  gather_facts: false

  tasks:
    - name: Run show arp Command
      raw: "show arp"
      register: output
    - name: Display Output on the Console
      debug: var=output

COMMAND TO RUN THE SCRIPT: ansible-playbook <script_name>.yml -u <username> -k
