---
- name: Gathering User-Level Details from the device
  hosts: all
  gather_facts: false
  connection:local

  tasks:
    - name: Run Show Commands
      ios_command:
        commands:
          - show version
          - show ip int br
      register: output
    - name: Display Output on the Console
      debug: var=output
 
 #COMMAND TO RUN THE SCRIPT: ansible-playbook <script_name>.yml -u <username> -k
