---
- name: Manage Network Devices
  hosts: all
  gather_facts: false
  connection: local

  vars:
    dev_details:
      username: dilraj
      password: dilraj
      authorize: yes

  tasks:
    - name: Run the Configuration Commands
      ios_config:
        provider: "{{dev_details}}"
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
      register: output
    - name: Display the Output
      debug: var=output

#COMMAND TO RUN THE SCRIPT: ansible-playbook <script_name>.yml
